### PR TITLE
New Sql Preview webview implementation with multi-doc PRQL Sql Preview support

### PR DESCRIPTION
**Pull request by RandomFractals**
- Implement new Sql Preview webview panel class as described in #60
- Add Sql Preview WebviewPanelSerializer to restore Sql Previews on vscode reload (#102)
- Add multi-doc PRQL SQL Preview support and active PRQL editor/Sql Preview reveal/linking (#108)
- Refine Sql copy to Clipboard messaging and support of multiple Sql Previews (#109)
- Rework Sql Preview html template, js and and css

### CODE REVIEW

**Comment by aljazerzen** [comment]
Damn, this is an impressive list of commits, kudos!

**Comment by RandomFractals** [comment]
Would have been better to see them in main branch too. Maybe we can do that next time.

Most of those changes were new web view implementation related, and I patched some of the questionable display issues and behavior in other parts of extension related to sql preview webview.

**Comment by aljazerzen** [comment]
But they reached main? Would you want to see them not squashed?

**Comment by RandomFractals** [comment]
yes. as I mentioned in discord, refactors like this I'd rather see individual commits in main.

We should enable that option in this repo Settings for such occasions.

**Comment by max-sixty** [comment]
> We should enable that option in this repo Settings for such occasions.

Done!

**Comment by max-sixty** [comment]
Really looking forward to trying this out!

**Pull request merged**
