### PR TITLE
add prql extension features list and config section to docs

### PR DESCRIPTION
**Pull request by RandomFractals**
to cover the basics in docs for #76

### CODE REVIEW

**Comment by max-sixty** [comment]
Looks good, thanks a lot @RandomFractals 

To the extent you want tweak-y feedback:
- Do we have intellisense?
- I find the dark theme worse on the light background of GitHub

**Comment by RandomFractals** [comment]
There is prql language config and grammar. VSCode draws keywords for intellisense from those configs.

We can change extension images to use light background. I've tried to change aspect ratio for better display in marketplace and still don't like the final outcome.

**Comment by max-sixty** [comment]
> There is prql language config and grammar. VSCode draws keywords for intellisense from those configs.

IIUC intellisense is more than syntax highlighting — it requires semantic understanding of the language so the editor can suggest completions https://code.visualstudio.com/docs/editor/intellisense.

(Though it's high on our roadmap — i.e. "Developer ergonomics — LSP" on https://prql-lang.org/roadmap/ !)

**Comment by RandomFractals** [comment]
yeah, tbh, I would suggest you add PRQL snippets. I like those more ...

Example: https://marketplace.visualstudio.com/items?itemName=sadeghpm.sql-snippets

I actually use my little know [Snippets Viewer](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.snippets-viewer) extension when I explore new custom languages in vscode, if they come with snippets.

Feel free to remove that part from readme in the next update.

**Pull request merged**
