### PR TITLE
build: Add pre-commit

### PR DESCRIPTION
**Pull request by max-sixty**
This should automate some of the formatting changes folks are doing. From https://github.com/PRQL/prql-vscode/pull/49#discussion_r1097835226

### CODE REVIEW

**Comment by max-sixty** [comment]
This uses the standard `prettier` formatting that we use in the main repo. If anyone has different preferences (e.g. @RandomFractals maybe this chooses something different re quotes?), then feel very free to change it.

**Comment by max-sixty** [comment]
> I find single quoted strings cleaner and easier to read, but that's a personal preference and you can set the code standards to match your other TypeScript projects.

I would have a preference to have automated formatting for the project maintenance, but if you want to change the defaults / use a different formatter, then that's very welcome, please feel free to change.

And if you have a v strong preference, we can revert and go back to manual formatting.

**Comment by RandomFractals** [comment]
It's not about manual formatting. I do use auto-format in vscode and `eslint`.

Pre-check/pre-commit checks and bot changes can be somewhat annoying when they happen on code commit and annotate commit comments, or rewrite neatly cleaned up code formatting and changes.

Let's just set the single quote strings rule, or remote ' -> " pre-commit bot changes for now, if you don't mind. Most vscode ext. TS devs use ' in import refs, etc.

**Comment by max-sixty** [comment]
> Pre-check/pre-commit checks and bot changes can be somewhat annoying when they happen on code commit and annotate commit comments, or rewrite neatly cleaned up code formatting and changes.
>
> Let's just set the single quote strings rule, or remove that ' -> " pre-commit bot changes rule for now, if you don't mind. Most vscode ext. TS devs use ' in import refs, etc.

To confirm, are you OK with the pre-commit with `'`s? I added you as the reviewer on https://github.com/PRQL/prql-vscode/pull/64; feel free to reject if you'd prefer not to have it.

**Pull request merged**
